config/routes.rb
Rails.application.routes.draw do
  #imposto controller personalizzati in app/controllers/users invece che quelli di devise
  devise_for :users, controllers: { sessions: 'users/sessions',
                                    registrations: 'users/registrations',
                                    confirmations: 'users/confirmations',
                                    passwords: 'users/passwords'}

  get '/users/profile/:id' => 'home#profile', :as => 'profile'
  #get '/users/profile/:id' => 'home#show_profile', :as => 'show_profile' #serve l'id?

  get '/admin_panel' => 'home#admin_panel', :as => 'admin_panel'

  resources :ads
  resources :favourites

  get '/profile/wish_list' => 'ads#wish', :as => 'wish_list'
  get '/profile/gift_list' => 'ads#gift', :as => 'gift_list'

  get '/ads_list' => 'home#ads_list', :as => 'ads_list'
  get '/books_results' => 'home#books_results', :as => 'books_results'
  get '/users_list' => 'home#users_list', :as => 'users_list'

  devise_scope :user do
    post '/users_list/banned/:id', to: 'users/registrations#banned_user', :as => 'banned_user'
    post '/users_list/admin/:id', to: 'users/registrations#admin_user', :as => 'admin_user'
    post '/users_list/booklover/:id', to: 'users/registrations#booklover_user', :as => 'booklover_user'
    match 'users/:id' => 'users/registrations#admin_destroy_user', :via => :delete, :as => :admin_destroy_user
  end

  # CHATS_CONTROLLER
  post 'send_message', to:'chats#receive'
  post 'delete_chat', to:'chats#delete_chat'
  post 'create_chat', to:'chats#create_chat'

  mount ActionCable.server, at: '/cable'

  root :to => "home#welcome"
  #get '*path' => redirect('/') DA LASCIARE

  resources :notifications, only: [:index]

end

app/models/favourite.rb
class Favourite < ApplicationRecord
    belongs_to :user
    validates :user_id, :presence => true
    validates_associated :user
    belongs_to :ad
    validates :ad_id, :presence => true
    validates_associated :ad
end

app/controllers/favourites_controller.rb
class FavouritesController < ApplicationController
    
    def new
    end

    def show
    end

    def create
        ad_id = params[:id][:book]
        if Favourite.where(:user_id => current_user.id, :ad_id => ad_id)[0]
            flash[:alert] = 'Annuncio Già presente nella tua lista!'
            redirect_to profile_path(:id => current_user.id)
        else
            favourite = Favourite.create!(:user_id => current_user.id, :ad_id => ad_id)
            flash[:notice] = "Book added to the list"
            redirect_to profile_path(:id => current_user.id)
        end
    end

    def index
        @favourites = Favourite.where(:user_id => current_user.id)
    end

    def destroy
        id = params[:id]
        Favourite.destroy(id)
        flash[:notice] = 'Ad removed'
        redirect_to favourites_path
    end
end

app/helpers/favourites_helper.rb
module FavouritesHelper
end

app/views/favourites/index.html.erb
<!-- Mostra la wish list dell'utente che gli passo dal profilo -->

<h3 style="text-align:center"> My Favourite List </h3>        <!-- , sono nel mio profilo -->

<div class="ad_container" id= "Favourites_listpage">
<% @favourites.each do |relation| %>
    <div class="ad_info">
        <% book = Ad.find(relation.ad_id) %>
        <% owner = User.find(book.user_id) %>
        <%= image_tag(book.link_to_coverbook) %>
        <br>
        <h7 style="color:green"> Owner of the ad: </h7><%= link_to "#{owner.username}", profile_path(:id => owner.id)%>
        <br>
        <h7 style="color:green"> Title: </h7><%= book.book_title %>
        <br>
        <h7 style="color:green"> Authors: </h7><%= book.book_authors.tr('[', '').tr(']','').tr('"', '') %>
        <br>
        <h7 style="color:green"> Publisher: </h7><%= book.publisher %>
        <br>
        <h7 style="color:green"> Identifier: </h7><%= book.identifier.tr('[', '').tr(']','').tr('"', '').tr(',','') %>
        <br>
        <%= link_to "Delete",favourite_path(:id => relation.id) , :method => :delete %>
        <br><br>
    </div>
<% end %>
</div>