config/routes.rb
Rails.application.routes.draw do
  #imposto controller personalizzati in app/controllers/users invece che quelli di devise
  devise_for :users, controllers: { sessions: 'users/sessions',
                                    registrations: 'users/registrations',
                                    confirmations: 'users/confirmations',
                                    passwords: 'users/passwords'}

  get '/users/profile/:id' => 'home#profile', :as => 'profile'
  #get '/users/profile/:id' => 'home#show_profile', :as => 'show_profile' #serve l'id?

  get '/admin_panel' => 'home#admin_panel', :as => 'admin_panel'

  resources :ads
  resources :favourites

  get '/profile/wish_list' => 'ads#wish', :as => 'wish_list'
  get '/profile/gift_list' => 'ads#gift', :as => 'gift_list'

  get '/ads_list' => 'home#ads_list', :as => 'ads_list'
  get '/books_results' => 'home#books_results', :as => 'books_results'
  get '/users_list' => 'home#users_list', :as => 'users_list'

  devise_scope :user do
    post '/users_list/banned/:id', to: 'users/registrations#banned_user', :as => 'banned_user'
    post '/users_list/admin/:id', to: 'users/registrations#admin_user', :as => 'admin_user'
    post '/users_list/booklover/:id', to: 'users/registrations#booklover_user', :as => 'booklover_user'
    match 'users/:id' => 'users/registrations#admin_destroy_user', :via => :delete, :as => :admin_destroy_user
  end

  # CHATS_CONTROLLER
  post 'send_message', to:'chats#receive'
  post 'delete_chat', to:'chats#delete_chat'
  post 'create_chat', to:'chats#create_chat'

  mount ActionCable.server, at: '/cable'

  root :to => "home#welcome"
  #get '*path' => redirect('/') DA LASCIARE

  resources :notifications, only: [:index]

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    #utenti non registrati possono accedere alla pagina welcome e ads_list
    skip_before_action :authenticate_user!, :only => [:welcome, :ads_list]

    def welcome
        #@matches_ads = lista annunci 'vicini'
        #@title = titolo da mostrare 
        if current_user
            user = current_user
            ads_not_user = Ad.where.not(:user_id => user.id)
            #cerco i matches cap/radius da mostrare in home
            @matches_ads = home_ads(ads_not_user)
            @title = "Recent ads close to me"
            if @matches_ads.empty?
                #se non risultano matches passo tutti gli annunci e cambio titolo
                @matches_ads = Ad.all
                @title = "Recent ads"
            end
        else
            @matches_ads = Ad.all
            @title = "Recent ads"
        end
    end
    
    def profile
        @user = User.find(params[:id])
        @chats = @user.chats
        @aux = {} # serve per memorizzare l'altro utente della chat
                  # all'interno della view
        #@c = @user.chats.first

        #per visualizzare la mappa cap
        maps_key = "AIzaSyDGDP6T-EYABI8GMdbuujMJKaCm37fyBss"
        @uri = URI("https://maps.googleapis.com/maps/api/staticmap")
        params = {"center" => "#{@user.cap} italy", "size" => "200x200", "zoom" => "11","key" => "#{maps_key}"}
        @uri.query = URI.encode_www_form(params)
    end

    def admin_panel
        if current_user.role == 'booklover' || current_user.role == 'banned'
            redirect_to root_path, :flash => { :error => "you haven't permission" }
        end
    end

    def ads_list
        @ad = params[:search][0]
        @ads = Ad.where( "book_title iLIKE?", "%#{@ad}%") #ORDINARE?
        if @ads.size.zero?
            flash[:alert] = "No result found"
            redirect_to root_path
        end
    end

    def users_list
        @user = params[:search][0] 
        @users = User.where( "username iLIKE?", "%#{@user}%") #ORDINARE?
        if @users.size.zero?
            flash[:alert] = "No result found"
            redirect_to root_path
        end
    end

    def books_results
        book = params[:search][0].downcase   #uso il downcase per eliminare le ricerche case-sensitive
        uri = URI('https://www.googleapis.com/books/v1/volumes')
        params = {:q => book, :maxResults => 24}
        uri.query = URI.encode_www_form(params)
        @res = Net::HTTP.get_response(uri)
        if JSON.parse(@res.body)['error']  #controllo se l'utente prova a fare una ricerca senza passare parametri
            flash[:alert] = "You should enter something!"
            redirect_to profile_path(current_user.id)
        end
    end

    private
    #per costruire l'array di annunci vicini
    def home_ads(ads_not_user)
        @matches_ads = Array.new
        ads_not_user.all.each  do |ad|
            if Ad.matches_user(ad, current_user.id)
                @matches_ads.push(ad)
            end
        end
        return @matches_ads
    end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_chat.html.erb
<% if @chats %> <!-- ho aggiunto un controllo perché nel caso di show_profile non passo le chat -->

    <% @chats.each do |c| %>
        <div class="col-md-8 chat_div" id=<%= c.id %> >
            <div class="col-md-12 list-group-item list-group-item-action active chat_top">
                <input type=button name="close_chat"  value=close>
            </div>
            <ul class="jumbotron message_box">
                <% c.messages.each do |m|%>
                    <% if m.from?.username == @user.username%>
                        <li class="sent_message">

                            <p class=message_text> <%= m.text%> </p>
                        </li>
                    <% else %>
                        <li class="received_message">

                            <p class=message_text> <%= m.text%> </p>
                        </li>
                    <% end %>
                <% end %>
            </ul>
            <textarea class="form-control input_box"></textarea>
        </div>
    <%end%>
<% end %>

app/views/home/_chats_index.html.erb
<% if @chats %> <!-- ho aggiunto un controllo perché nel caso di show_profile non passo le chat -->

<ul id=chats_list class="col-md-12 group-list chat_list">

    <li class="list-group-item list-group-item-action active chat_list_title">
        <h2> Chats </h2>
    </li>

    <% @chats.each do |c| %>
    <li class="list-group-item list-group-item-action chat_list_item" id="chat_item_<%= c.id%>">
        <meta name="chat_id" content= <%= c.id %> >
        <% if @user.username == c.owner.username then @aux = c.guest else @aux = c.owner end%>
        <%= image_tag(@aux.image.url, alt: 'Image',class: 'chat_user_img') %>
        <p>
            <%= @aux.username %>
        </p>

        <input type="button" class="delete_chat btn-sm" value="delete">
    </li>
    <% end %>

    </ul>
<% end %>

app/views/home/admin_panel.html.erb
<div class="admin-panel center">


    <div class="col-md-12 list-group">
    <h4 class="list-group-item list-group-item-action active">
        All users
    </h4>
    <input type="text" id="users_searchbar" placeholder="Search for names..">
    <ul class="list-group admin_users_list" id = "admin_users_list">
        <% User.all.order('username').each do |user| %>
            <% if user.role != "superadmin" %>
                <% if user.id != current_user.id %>
                    <li class="list-group-item list-group-item-action">
                        <%= link_to "#{user.username}".capitalize, profile_path(user.id) %>
                            <% if can? :manage_user, user %>
                                <br>
                                Role: <%= user.role.capitalize%><br>
                                <%= link_to "Admin user", admin_user_path(user.id), :method => 'post', class:"btn btn-warning"%>
                                <%= link_to "Booklover user", booklover_user_path(user.id), :method => 'post', class:"btn btn-success"%>
                                <%= link_to "Bann user", banned_user_path(user.id), :method => 'post', class:"btn btn-danger"%>
                            <% end %>
                            <% if can? :admin_destroy_user, user %>
                                <%= link_to "Delete user", admin_destroy_user_path(user.id), :method => 'delete', class:"btn btn-danger"%>
                            <% end %>
                        <br><br>
                    </li>
                <% end %>
            <% end %>
        <% end %>
    </ul>
    </div>
    
</div>

app/views/home/ads_list.html.erb
<!-- Mostro la lista di tutti gli Ads e il link al profilo del proprietario dell'annuncio -->
<div class="center" id="ads_listpage">
  <h3>Ads</h3> 
  <p>
  <%= render partial: "./ads_list", locals: { ads: @ads, view: "list" } %>
</div>

app/views/home/books_results.html.erb
<!-- Mostra la lista di Libri trovati con google books -->

<h3 class="results_title" id="books_result"> Books found </h3>

<div class="book_container">
    <% books = JSON.parse(@res.body)['items'] %>
    <% books.each do |book| %>

    <div class="book_info">
        <% if book['volumeInfo']['imageLinks']%>
            <% if book['volumeInfo']['imageLinks']['thumbnail']%>
                <%= image_tag(book['volumeInfo']['imageLinks']['thumbnail']) %>
            <% elsif book['volumeInfo']['imageLinks']['smallThumbnail'] %>
                <%= image_tag(book['volumeInfo']['imageLinks']['smallThumbnail'])%>
            <% end %>
        <% end %>
        <br>
        <% if book['volumeInfo']['title'] %>
            <h7> Title: </h7>
            <%= book['volumeInfo']['title'] %>
        <% else %>
            <h7> Title: not specified </h7>
        <% end %>
        <br>
        <% if book['volumeInfo']['authors'] %>
            <h7> Authors: </h7>
            <% book['volumeInfo']['authors'].each do |author| %>
                <%= author %>
            <% end %>
        <% else %>
            <h7> Authors: not specified </h7>
        <% end %>
        <br>
        <% if book['volumeInfo']['publisher'] %>
            <h7> Publisher: </h7>
            <%= book['volumeInfo']['publisher'] %>
        <% else %>
            <h7> Publisher: not specified </h7>
        <% end %>
        <br>
        <% if book['volumeInfo']['industryIdentifiers']%>
            <% if book['volumeInfo']['industryIdentifiers'][0]['type'] %>
                <h7> Identifier: </h7>
                <%= book['volumeInfo']['industryIdentifiers'][0]['type'] %>
            <% end %>
            <% if book['volumeInfo']['industryIdentifiers'][0]['identifier'] %>
                <%= book['volumeInfo']['industryIdentifiers'][0]['identifier'] %>
            <% end %>
        <% else %>
            <h7> Identifier: not specified </h7>
        <% end %>
        <br>
        <h7> Aggiungi a:</h7><br>
        <!-- link per aggiungere il libro alle liste -->
        <%= link_to "Wish", ads_path(:book =>{:id => book, :list_type => 0}), :method => :post , class:"text-warning"%>
        <%= link_to "Gift", ads_path(:book =>{:id => book, :list_type => 1}), :method => :post , class:"text-danger"%>
        <br>
        <br>
    </div>
    <% end %>

app/views/home/profile.html.erb
<div id='profilepage'>
<!-- IMPORTANTE per far funzionare i channels -->
<meta name='userid' content="<%=current_user.id%>">
<!-- ######################################## -->

<%if @user.id == current_user.id %>
    <%= render partial: "chat", locals: {user:@user, chats:@chats} %>
<%end%>

<div class="col-md-8 left_panel">

    <div class="col-md-4 picture_box">
        <%= image_tag(@user.image.url, alt: 'Image',class: 'user_img') %>
    </div>



    <div class="col-md-4 info_box">
            <br><br>
            Name: <small class="text-success"><%= @user.name %><br></small>
            Surname: <small class="text-success"><%= @user.surname %><br></small>
            Username: <small class="text-success"><%= @user.username %><br></small>
            Email: <small class="text-success"><%= @user.email %><br></small>
            <% if @user.id == current_user.id %>
                Cap: <small class="text-success"><%= @user.cap %><br></small>
                Radius: <small class="text-success"><%= @user.radius %><br></small>
            <% end %>
            
            <%if @user.id == current_user.id %>
                <%= button_to "Edit profile", edit_user_registration_path, :method => 'get', class: "btn-sm btn-warning"%>
            <% end %>
  
    </div>

    <div class="col-md-4 map_box">
        <%= image_tag(@uri,class:"map_img") %>
    </div>


    <div class="col-md-4 actions">
        <div class="list-group">
            <p class="list-group-item list-group-item-action active">
            <% if @user.id.to_s == current_user.id.to_s %>    <!-- se l'id passato e lo user corrispondono -->
                MY LIBRARY                                    <!-- , sono nel mio profilo -->
            <% else %>
                <% owner = User.find(@user.id).username %>
                <%= owner %>'s LIBRARY
            <% end %>
            </p>
            <%if @user.id == current_user.id %>
                <%= link_to "Favourite list", favourites_path, class:"list-group-item list-group-item-action"  %>
            <% end %> <!--non voglio mostrare i favoriti e la modifica del profilo delgi altri utenti -->
            <%= link_to "Wish list", wish_list_path(:list_type => 0, :id => @user.id),class:"list-group-item list-group-item-action"%>
            <%= link_to "Gift list", gift_list_path(:list_type => 1, :id => @user.id),class:"list-group-item list-group-item-action"%>

        </div>
    </div>

    <div class="col-md-8 search_div">
    <%if @user.id == current_user.id %>
            <%= form_tag(books_results_path, :method => "get", id: "search-form", class: "form-group") do %>
            <%= text_field :search, params[:search], placeholder: "Search Books" %>
            <%= submit_tag "Search" ,class:"btn-sm btn-secondary my-2 my-sm-0" %>
            <% end %>
    <%end%>
    </div>

</div>


<div class="col-md-4 right_panel">
    <%if @user.id == current_user.id %>
        <%= render partial: "chats_index", locals: { chats: @chats } %>
    <%end%>
</div>

</div>

app/views/home/users_list.html.erb
<div class="center" id="users_listpage">

    <!-- IMPORTANTE per far funzionare i channels -->
    <meta name='userid' content="<%=current_user.id%>">
    <!-- ######################################## -->

    <h3>Users</h3> 

    <ul class="list-group">
        <% @users.order("name").each do |user|%>
            <% if user.role != "superadmin"%>
                <li class="list-group-item d-flex  align-items-center">
                    <meta name="user_id" content="<%= user.id %>">
                    <%= image_tag(user.image.url, alt: 'Image',class: 'list_user_img') %>
                    <%= link_to "#{user.username}",profile_path(user.id) %>
                    <button  type="button" class="btn btn-success start_chat">Chat</button>
                </li>
            <%end%>
        <% end %>
    </ul>
</div>

app/views/home/welcome.html.erb
<div class="home-container center" id="homepage">

	<div class="col-md-6">
		<%= form_tag(ads_list_path, :method => "get", id: "search-form", class: "form-group") do %>
		<%= text_field :search, params[:search], placeholder: "Search Ads", id:"adsform"%>
		<%= submit_tag "Search", id: "searchads" %>
		<% end %>
	</div>

	<div class="col-md-6" id="searchuser">
		<%= form_tag(users_list_path, :method => "get", id: "search-form2", class: "form-group") do %>
		<%= text_field :search, params[:search], placeholder: "Search User", id:"textform"%>
		<%= submit_tag "Search", id: "searchbutton"%>
		<% end %>
	</div>

	<h3>
		<%= @title %><br>
	</h3>

	<%= render partial: "./ads_list", locals: { ads: @matches_ads, view: "welcome" } %>
</div>