config/routes.rb
Rails.application.routes.draw do
  #imposto controller personalizzati in app/controllers/users invece che quelli di devise
  devise_for :users, controllers: { sessions: 'users/sessions',
                                    registrations: 'users/registrations',
                                    confirmations: 'users/confirmations',
                                    passwords: 'users/passwords'}

  get '/users/profile/:id' => 'home#profile', :as => 'profile'
  #get '/users/profile/:id' => 'home#show_profile', :as => 'show_profile' #serve l'id?

  get '/admin_panel' => 'home#admin_panel', :as => 'admin_panel'

  resources :ads
  resources :favourites

  get '/profile/wish_list' => 'ads#wish', :as => 'wish_list'
  get '/profile/gift_list' => 'ads#gift', :as => 'gift_list'

  get '/ads_list' => 'home#ads_list', :as => 'ads_list'
  get '/books_results' => 'home#books_results', :as => 'books_results'
  get '/users_list' => 'home#users_list', :as => 'users_list'

  devise_scope :user do
    post '/users_list/banned/:id', to: 'users/registrations#banned_user', :as => 'banned_user'
    post '/users_list/admin/:id', to: 'users/registrations#admin_user', :as => 'admin_user'
    post '/users_list/booklover/:id', to: 'users/registrations#booklover_user', :as => 'booklover_user'
    match 'users/:id' => 'users/registrations#admin_destroy_user', :via => :delete, :as => :admin_destroy_user
  end

  # CHATS_CONTROLLER
  post 'send_message', to:'chats#receive'
  post 'delete_chat', to:'chats#delete_chat'
  post 'create_chat', to:'chats#create_chat'

  mount ActionCable.server, at: '/cable'

  root :to => "home#welcome"
  #get '*path' => redirect('/') DA LASCIARE

  resources :notifications, only: [:index]

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Flealibrary</title>
    <%= csrf_meta_tags %>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <%= stylesheet_link_tag "https://bootswatch.com/4/sketchy/bootstrap.min.css" %>
  </head>

  <body>

  <div class="col-md-12 flash_container">
    <% if flash[:notice] %>
      <div class="alert alert-dismissible alert-success"><%= flash[:notice] %></div>
    <% end %>
    <% if flash[:alert] %>
      <div class="alert alert-dismissible alert-warning"><%= flash[:alert] %></div>
    <% end %>
    <% if flash[:error] %>
      <div class="alert alert-dismissible alert-danger"><%= flash[:error] %></div>
    <% end %>
  </div>

  <h1 class="display-3 title">FLEA LIBRARY</h1>

  <div class="col-md-12 topnav">
    <%= button_to "HOME", root_path, :method => 'get', class: "btn-lg btn-warning" %>
        <%if user_signed_in?%>
          <% user = current_user %>
          <%= button_to "#{user.username.upcase}", profile_path(user.id), :method => 'get', class: "btn-lg btn-success profile_btn"%>
          <%= button_to "Notifications: #{user.notifications_counter}", notifications_path, :method => 'get', class:"btn-lg btn-outline-primary notifications_btn", id:"notifications_btn"%>
            <% if (current_user.role == 'admin' || current_user.role == 'superadmin') %>
              <%= button_to "Admin panel", admin_panel_path, :method => 'get', class: "btn-lg btn-outline-danger admin_btn", id: "adminbutton"%>
            <% end %>
          <%= button_to "Log out", destroy_user_session_path, :method => 'delete', class: "btn-lg btn-danger logout_btn", id: "logoutbutton" %>
        <%else%>
          <%= button_to "Log in", new_user_session_path, :method => 'get', class: "btn-lg btn-success login_btn" , id: "loginbutton"%>
          <%= button_to "Sign up", new_user_registration_path, :method => 'get', class: "btn-lg btn-info signin_btn", id: "signupbutton" %>
        <%end%>
  </div>

  <% if user.present? && user.role == "banned" %>
    <div class="col-md-12 center">
      <p class="text-danger">YOU ARE BANNED, YOU CAN DO NOTHING :) </p>
      <%= button_to "Cancel account", registration_path(User), data: { confirm: "Are you sure?" }, method: :delete , class:"btn btn-danger"%>
    </div>
  <% else %>
    <%= yield %>
  <% end %>

</body>
</html>